export const CATEGORIES = {
  rpg: {
    label: "Rol / Fantasía",
    prefixes: [
      "Aer",
      "Bel",
      "Cal",
      "Dor",
      "El",
      "Fin",
      "Gal",
      "Har",
      "Ith",
      "Jar",
      "Kel",
      "Lun",
      "Mor",
      "Ner",
      "Or",
      "Pel",
      "Qir",
      "Ryn",
      "Sol",
      "Tor",
    ],
    middles: [
      "an",
      "or",
      "en",
      "is",
      "ar",
      "il",
      "us",
      "ath",
      "ion",
      "el",
      "ir",
    ],
    suffixes: [
      "dor",
      "wen",
      "thas",
      "mar",
      "gorn",
      "dil",
      "wyn",
      "nor",
      "ion",
      "rus",
      "mir",
      "thil",
    ],
  },
  shooter: {
    label: "Shooter",
    prefixes: [
      "Ghost",
      "Viper",
      "Zero",
      "Alpha",
      "Blaze",
      "Raptor",
      "Strike",
      "Delta",
      "Nova",
      "Echo",
      "Reaper",
      "Shadow",
      "Specter",
    ],
    middles: ["_", "-", "X", "", "Z", "Rx"],
    suffixes: [
      "01",
      "99",
      "Pro",
      "Elite",
      "Sniper",
      "Shot",
      "Ops",
      "Core",
      "Edge",
    ],
  },
  br: {
    label: "Battle Royale",
    prefixes: [
      "Sky",
      "Storm",
      "Grim",
      "Wild",
      "Iron",
      "Titan",
      "Prime",
      "Blade",
      "Rogue",
      "Pulse",
      "Venom",
      "Apex",
      "Crimson",
      "Vortex",
      "Phantom",
    ],
    middles: ["", "-", "_", "", "X", "Rx", "Z"],
    suffixes: [
      "Survivor",
      "Runner",
      "King",
      "Queen",
      "Slayer",
      "Champion",
      "Drift",
      "Edge",
      "Hunter",
      "Breaker",
      "Master",
    ],
  },
};

export const STYLE_MODS = {
  fantasy: { label: "Fantasía" },
  futuristic: { label: "Futurista" },
  grim: { label: "Oscuro" },
  silly: { label: "Divertido" },
};

export default { CATEGORIES, STYLE_MODS };
